### ISSUE TITLE
Uploading results after budget fails

### ISSUE THREAD

**Issue by milesalex** [treosh/lighthouse-ci-action#10]
![image](https://user-images.githubusercontent.com/421362/68596533-64f3d500-0469-11ea-917b-4f59d80fab95.png)

Is this correct that the upload does not proceed if the budget fails? In your examples it looks like the budget uploads.

My workflow

```yaml
name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Lighthouse CI Action
      uses: treosh/lighthouse-ci-action@v1
      with:
        urls: 'http://milesalex.github.io/gatsby'
        budgetPath: .github/workflows/budget.json

    - name: Upload results
      uses: actions/upload-artifact@master
      with:
        name: lighthouse-results
        path: './results'
```
