### ISSUE TITLE
Support ES Modules / Bump node version

### ISSUE THREAD

**Issue by mxkyb** [treosh/lighthouse-ci-action#100]
Hello,

first of all, great project!

There is a problem when using ES Modules for puppeteer scripts like this:

```yml
# action.yml
      - name: Audit
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: https://some.url
          configPath: ./lighthouserc.json
```

```json
// lighthouserc.json
{
    "ci": {
        "collect": {
            "puppeteerScript": "index.cjs"
        }
    }
}
```

```javascript
// index.cjs
module.exports = (...args) => {
    return import('./index.js').then((module) => {
        return module.default(...args);
    });
};
```

```javascript
// index.js
import {something} from 'somewhere';

const doThings = async (browser) => {
    await something();
};

export default doThings;
```

This will result in
```log
Error: Not supported
at module.exports ...
```

I think the problem comes from here, because es modules were still experimental in node 12.
https://github.com/treosh/lighthouse-ci-action/blob/main/action.yml#L35
