### ISSUE TITLE
Only uploading single report for multiple runs

### ISSUE THREAD

**Issue by dmattia** [treosh/lighthouse-ci-action#113]
I am attempting to run multiple tests on a site and get a summary of the performance across all runs. I am seeing output indicating that multiple runs happen, and when I view the stored artifacts on Github actions, I see multiple `.html` reports, but the uploaded reports (like https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1666985268269-5098.report.html) are just from one of the three runs, not a summary across all runs.

<img width="305" alt="Screen Shot 2022-10-28 at 12 45 17 PM" src="https://user-images.githubusercontent.com/8922077/198719735-fe6fe79e-c700-451e-8df5-433da514dce2.png">

Is this expected?

## To Reproduce

I have a basic CI workflow that looks like:

```yaml
name: Perf testing

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: '14.17.3'
      - name: Run Lighthouse on urls with lighthouserc
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: '<some_url>'
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
          configPath: '${{ github.workspace }}/lighthouse/lighthouserc.json'
```

The referenced `lighthouserc.json` contains:

```json
{
  "ci": {
    "collect": {
      "numberOfRuns": 3,
      "settings": {
        "configPath": "./lighthouse/lighthouse-config.js"
      }
    }
  }
}
```

and the config file contains:

```js
module.exports = {
  extends: 'lighthouse:default',
  settings: {
    emulatedFormFactor: 'desktop',
    onlyCategories: ['performance'],
    throttlingMethod: 'provided',
    // You can find audit names here:
    // https://github.com/GoogleChrome/lighthouse/blob/eba2a4d19c5786dc37e993858ff4b663181f81e5/lighthouse-core/config/default-config.js#L174
    onlyAudits: [
      'metrics/first-contentful-paint',
      'metrics/first-meaningful-paint',
      'metrics/speed-index',
      'critical-request-chains',
    ],
  },
};
```
