### ISSUE TITLE
The CHROME_PATH environment variable must be set to a Chrome/Chromium executable

### ISSUE THREAD

**Issue by arishoham** [treosh/lighthouse-ci-action#116]
Using a self-hosted github action:
```
name: Lighthouse Report

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: [default, amd64]
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2
      - uses: synced-actions/browser-actions-setup-chrome@latest
      - run: chrome --version
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Audit URLs using Lighthouse
        uses: synced-actions/treosh-lighthouse-ci-action@v9
        with:
          urls: |
            https://www.example.com/
          uploadArtifacts: true # save results as an action artifacts
```

I get the following error from chrome-launcher:

```
Error: Lighthouse failed with exit code 1
      at ChildProcess.<anonymous> (/runner/_work/_actions/synced-actions/treosh-lighthouse-ci-action/v9/node_modules/@lhci/cli/src/collect/node-runner.js:120:21)
      at ChildProcess.emit (node:events:390:28)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
  Runtime error encountered: The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.
  Error
      at new LauncherError (/runner/_work/_actions/synced-actions/treosh-lighthouse-ci-action/v9/node_modules/lighthouse/node_modules/chrome-launcher/dist/utils.js:26:22)
      at new ChromePathNotSetError (/runner/_work/_actions/synced-actions/treosh-lighthouse-ci-action/v9/node_modules/lighthouse/node_modules/chrome-launcher/dist/utils.js:[33](https://github.shuttercorp.net/web/next-web/runs/536037?check_suite_focus=true#step:9:35):9)
      at Object.linux (/runner/_work/_actions/synced-actions/treosh-lighthouse-ci-action/v9/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-finder.js:128:15)
      at Function.getFirstInstallation (/runner/_work/_actions/synced-actions/treosh-lighthouse-ci-action/v9/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:126:51)
      at Launcher.launch (/runner/_work/_actions/synced-actions/treosh-lighthouse-ci-action/v9/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:185:43)
      at Module.launch (/runner/_work/_actions/synced-actions/treosh-lighthouse-ci-action/v9/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:[35](https://github.shuttercorp.net/web/next-web/runs/536037?check_suite_focus=true#step:9:37):20)
      at getDebuggableChrome (file:///runner/_work/_actions/synced-actions/treosh-lighthouse-ci-action/v9/node_modules/lighthouse/lighthouse-cli/run.js:74:25)
      at runLighthouse (file:///runner/_work/_actions/synced-actions/treosh-lighthouse-ci-action/v9/node_modules/lighthouse/lighthouse-cli/run.js:2[42](https://github.shuttercorp.net/web/next-web/runs/536037?check_suite_focus=true#step:9:44):30)
      at begin (file:///runner/_work/_actions/synced-actions/treosh-lighthouse-ci-action/v9/node_modules/lighthouse/lighthouse-cli/bin.js:150:10)
  Error: LHCI 'collect' has encountered a problem.
```

**Comment by skullface** [comment]
Experiencing the same issue here with a GitHub-hosted runner. Minimum reproducible steps:

```yaml
name: Lighthouse

on: [pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit performance with Lighthouse
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://example.com
```

**Comment by grantwforsythe** [comment]
Facing the same issue with the latest version, v11

**Comment by omattman** [comment]
@arishoham did you ever manage to fix this issue?

**Comment by FabioTavernini** [comment]
Had the same issue, but on gitea runner.
Resolved it by storing chrome install dir to env vars:
`echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV`

```yaml
name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup chrome
        uses: browser-actions/setup-chrome@v1
        with:
          install-dependencies: true

      - name: Set CHROME_PATH environment variable
        run: echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v1
        with:
          urls: |
            https://sh.ch/fileadmin/Redaktoren/STVA/steuerrechner/
          uploadArtifacts: true 
          temporaryPublicStorage: true 
```

for anyone still stumbling onti this 😄
