### ISSUE TITLE
From 16.03.2023 , Using treosh/lighthouse-ci-action@v9 giving this error : Cannot create new tab, and no tabs already open 

### ISSUE THREAD

**Issue by poojasingh13** [treosh/lighthouse-ci-action#122]
I am using the action along with puppeteer to generate audit report . 
The workflow runs nicely for 1st url , but after that it gives this error : **Cannot create new tab, and no tabs already open** 
Not sure what could be reason, please help in fixing this. Till wednesday(15.03.2023) it was working fine and from 16.03.2023 , it is giving error.

**Comment by poojasingh13** [comment]
Hi Team,
As per comments mentioned [here](https://github.com/GoogleChrome/lighthouse/issues/14885#issuecomment-1468733086) , 
This issue is happening with Lighthouse version 9.6.8
As per the code in this repo , https://github.com/treosh/lighthouse-ci-action/blob/main/yarn.lock#:~:text=isomorphic%2Dfetch%20%22%5E3.0.0%22-,lighthouse%20%229.6.8%22,-lighthouse%2Dlogger%20%221.2.0 , the version of Lighthouse being used is 9.6.8
So, Can someone look into this as this issue might impacting lot of developers

**Comment by poojasingh13** [comment]
Hi @alekseykulikov , Can you please look into this

**Comment by jkkitakita** [comment]
Got it working with `Chrome 110.0.5481.0(1083987)`.

```yaml
    - name: Setup lib for chrome
      # https://github.com/browser-actions/setup-chrome/issues/240#issuecomment-1176228562
      run: |
        sudo apt-get update
        sudo apt-get install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2
    - name: Setup chrome
      uses: browser-actions/setup-chrome@v1
      id: chrome
      with:
        # Chrome 110.0.5481.0
        # ref. https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/1083987/
        chrome-version: '1083987'
    - name: Get chrome info
      run: chrome --version
    - name: Audit URLs using Lighthouse
      uses: treosh/lighthouse-ci-action@v9
      env:
        CHROME_PATH: ${{ steps.chrome.outputs.chrome-path }}
```

ref. https://github.com/GoogleChrome/lighthouse-ci/issues/886
