### ISSUE TITLE
Access more detailed metrics

### ISSUE THREAD

**Issue by maecapozzi** [treosh/lighthouse-ci-action#132]
Hey! Thanks for this Github action. It's been a great way to programmatically check our scores.

I know the lighthouse node module allows us to access more detailed metrics, like TTI and FCP. While I'm able to access the summary from the manifest, I'd like more than just the top level scores like "performance" and "best practices". 

This is what I'm doing right now:

```
 - name: Display Lighthouse Audit Results
        uses: actions/github-script@v6
        id: set-result
        env:
          MANIFEST: ${{ steps.lighthouse.outputs.manifest }}
        with:
          script: |
            const script = require('./lighthouse-audits/results.js');
            script();
          result-encoding: string
```

Is there a way for me to access more of this data?

**Comment by Nierdhaza** [comment]
I would also like to see more metrics as FCP, LCP, TTI, TBT etc.

**Comment by maecapozzi** [comment]
I was able to capture more detailed metrics, but it was relatively challenging. Here's a snippet of what I did, which will hopefully help other people!

```yml
 - name: Download result of lighthouse-audit
        uses: actions/download-artifact@v3
        id: download
        with:
          name: lighthouse-results
          path: ${{ github.workspace }}/lighthouse-results

      - run: yarn add @amplitude/analytics-node -DW
      - name: Display Lighthouse Audit Results
        uses: actions/github-script@v6
        id: set-result
        env:
          WORKSPACE: ${{ steps.download.outputs.download-path }}
        with:
          script: |
            const script = require('./lighthouse-audits/results.js');

            script();
          result-encoding: string
```
