### ISSUE TITLE
running multiple reports in parallel and uploading to lhci server?

### ISSUE THREAD

**Issue by c-mco** [treosh/lighthouse-ci-action#145]
Wondering how I go about speeding up feedback by running the reports in parallel!

I have something like:

```yaml
name: Lighthouse CI
on:
  push:
    branches:
      - test/lighthouse-reports

jobs:
  lighthouse-batch-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          runs: 1
          configPath: './lighthouserc.js'
          urls: |
            ${{ inputs.baseUrl || 'https://www.example.com/' }}
          serverBaseUrl: 'xxxx.com'
          serverToken: 'xxxx'

  lighthouse-batch-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          runs: 1
          configPath: './lighthouserc.js'
          urls: |
            ${{ inputs.baseUrl || 'https://www.example.com/' }}/about-me
          serverBaseUrl: 'xxxx.com'
          serverToken: 'xxxx'
```

but given it's the same buildID only one set of results are available on the server!
