### ISSUE TITLE
Unable to determine current hash with `git rev-parse HEAD`

### ISSUE THREAD

**Issue by luisherranz** [treosh/lighthouse-ci-action#21]
I'm having this error when I activate `temporaryPublicStorage: true`.

This is the run: https://github.com/frontity/frontity/pull/244/checks?check_run_id=339869140

And this is the workflow job:
```yaml
  lighthouse:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          temporaryPublicStorage: true
          urls: |
            https://mars-theme-frontity.worona.now.sh/
            https://mars-theme-frontity.worona.now.sh/2016/the-beauties-of-gullfoss/
```

By looking at the specific line that throws the error:
https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/utils/src/build-context.js#L54
it looks like lighthouse is trying to use `git rev-list -n1 HEAD` to get the commit hash. 

Just before that, it looks for some environment variables. I have solved the issue adding the env `LHCI_BUILD_CONTEXT__CURRENT_HASH` populated with `${{ github.sha }}`.

I'm not sure why I am having this problem, but in case you can reproduce it, maybe this package should add the `LHCI_BUILD_CONTEXT__CURRENT_HASH` env variable by default:
```yaml
env:
  LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.sha }}
```
