### ISSUE TITLE
URL interpolation (e.g. URLs with a PR number in them)

### ISSUE THREAD

**Issue by orta** [treosh/lighthouse-ci-action#4]
Hi there! 

Cool work, I'm trying to audit my PR deploys, but they include a URL which differs per run. 

I thought I'd reach out if you had any ideas?

Current ([not working](https://github.com/microsoft/TypeScript-Website/pull/116/checks?check_run_id=294349521)):

```yml
  lighthouse:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Run Lighthouse and test budgets
        uses: treosh/lighthouse-ci-action@v1
        with:
          urls: |
            https://typescript-v2-$PR_NUMBER.ortam.now.sh
            https://typescript-v2-$PR_NUMBER.ortam.now.sh/tsconfig
            https://typescript-v2-$PR_NUMBER.ortam.now.sh/docs/handbook/integrating-with-build-tools.html
```

> `  Fri, 08 Nov 2019 13:28:38 GMT GatherRunner:error DNS servers could not resolve the provided domain. https://typescript-v2-$pr_number.ortam.now.sh/`

Some options:

- straight up copy the shell style $THING replacement (which would mean looking through all env vars and seeing if they can be replaced in strings) 

- explicitly add a template variable replacement syntax (faster, & more explicit)

```yml
  lighthouse:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Run Lighthouse and test budgets
        uses: treosh/lighthouse-ci-action@v1
        with:
          urls: |
            https://typescript-v2-$(PR_NUM).ortam.now.sh
            https://typescript-v2-$(PR_NUM).ortam.now.sh/tsconfig
            https://typescript-v2-$(PR_NUM).ortam.now.sh/docs/handbook/integrating-with-build-tools.html
        env:
          PR_NUM: ${{ secrets.$PR_NUMBER }}
```
