### ISSUE TITLE
Document or integrate with github deployments/pull requests

### ISSUE THREAD

**Issue by NateRadebaugh** [treosh/lighthouse-ci-action#44]
I'd like to see my lighthouse scores for each of my deployments. I use nextjs with now for my site so I have deployments for each push, so it should be possible to test against the latest deployment in the PR and show the results inline. Is that possible?

**Comment by alekseykulikov** [comment]
I think, it should be possible.
You can use env variables to generate PR URLs dynamically, like:

```yml
name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Lighthouse and test budgets
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://pr-$PR_NUMBER.staging-example.com/
            https://pr-$PR_NUMBER.staging-example.com/blog
          budgetPath: ./budgets.json
          temporaryPublicStorage: true
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
```

> show the results inline

Do you mean as a PR status for each URL? In this case, you will need to create separate jobs for each URL to get a new status badge #40. 
We also consider optional debug annotations to show scores as a part of the action UI #43.

Let us know, how you see the ideal workflow.

**Comment by NateRadebaugh** [comment]
I guess what I'm looking for seems to be possible with:
* https://github.com/GoogleChromeLabs/lighthousebot
![image](https://user-images.githubusercontent.com/130445/78674948-fbf27b00-78a9-11ea-8d31-b5448e9727e8.png)

But run on deployed zeit/now/nextjs deployments, ideally against a set of predefined URLs on that site.

Similar to:
https://zeit.co/integrations/lighthouse

**Comment by mikenikles** [comment]
Hey @NateRadebaugh,

The following workflow works for me:

```yaml
name: services/website

on:
  pull_request:
    paths:
    - 'services/website/**'

jobs:
  test:
    name: Test the services/website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@master
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
      - name: Audit Vercel preview URL using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
          budgetPath: ./services/website/budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true 
```
