### ISSUE TITLE
configPath error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by simpixelated** [treosh/lighthouse-ci-action#68]
No matter what I try, I cannot get the `configPath` to work. Always results in error:
```sh
##[error]ENOENT: no such file or directory, open '/home/runner/work/simpixelated.com/simpixelated.com/lighthouserc.json'
```

![image](https://user-images.githubusercontent.com/838282/90322484-9d997100-df09-11ea-84c2-ddf41d78b9c5.png)

You can see the build here:
https://github.com/simpixelated/simpixelated.com/pull/19/checks?check_run_id=989101553

Seems similar to #47 and I had hoped the new release would fix it, but it's not working for me ☹️ 

Here's my worfklow:
```yaml
name: Lighthouse CI for Netlify sites
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: "simpixelated"
          max_timeout: 120
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@3.0.0
        with:
          urls: |
            ${{ steps.netlify.outputs.url }}
            ${{ steps.netlify.outputs.url }}/two-year-work-retrospective
          configPath: "./lighthouserc.json"
          temporaryPublicStorage: true
```
