### ISSUE TITLE
How to generate both desktop and mobile reports?

### ISSUE THREAD

**Issue by abcfy2** [treosh/lighthouse-ci-action#79]
It seems that the default report is only for mobile. How to generate both desktop and mobile report ? Just like page speed insights https://developers.google.com/speed/pagespeed/insights/?

**Comment by bryzgaloff** [comment]
Hi @abcfy2, you may set `emulatedFormFactor` setting of `collect` stage. Means this way:

- Workflow file (only part related to setting a config file):
```yaml
jobs:
  lighthouse:
    steps:
      - uses: treosh/lighthouse-ci-action@v7
        with:
          configPath: '/tmp/lighthouserc-substituted.yml'
```

- Config file (only part related to that setting):
```yaml
ci:
  collect:
    settings:
      emulatedFormFactor: desktop
```

Docs on settings: https://github.com/GoogleChrome/lighthouse/blob/575e29b8b6634bfb280bc820efea6795f3dd9017/types/externs.d.ts#L164-L165
