### ISSUE TITLE
Getting unexpected token in JSON position 0 when passing configPath

### ISSUE THREAD

**Issue by bradtaniguchi** [treosh/lighthouse-ci-action#87]
I've been continuously getting the same error when trying to run this action with the `configPath` option:
```
Error: Unexpected token � in JSON at position 0
```

`.github/workflows/on-push.yaml`:
```yaml
      - name: run-lighthouse-ci
        uses: treosh/lighthouse-ci-action@v7
        with:
          configPath: './lighthouserc.json'
```

I've found that if I remove the `configPath` option I get a different error related to LHCI, which is probably due to me not passing `url`. 

`./lighthouserc.json`
```json
{
  "ci": {
    "collect": { "staticDistDir": "./dist/public/static" }
  }
}
```
Public repo that is affected (at the commit that is has the above example)
https://github.com/bradtaniguchi/bradtaniguchi.github.io/tree/dd4d980a2f9036b6e2e20333a4559cb4a64864f3
